FROM golang:1.23-alpine AS build
WORKDIR /src
COPY go.mod ./
COPY cmd ./cmd
RUN CGO_ENABLED=0 go build -o /challenge-wrapper ./cmd/wrapper

FROM python:3.11-slim
COPY --from=build /challenge-wrapper /usr/local/bin/challenge-wrapper
ENV BITERRA_LISTEN_ADDR=:8080 BITERRA_UPSTREAM_PORT=3000
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/challenge-wrapper"]
